sudo: required
services:
  - docker

  before_install:
    - docker build -t vaibhavranjave/docker-react -f Dockerfile.dev .

    script:
      - docker run vaibhavranjave/docker-react npm run test -- --coverage